// src/features/assignment/components/AssignmentSummary.vue
<script setup lang="ts">
/**
 * AssignmentSummary.vue - Vue 3 버전
 * 이번 주 배정 현황 요약
 */
import { computed } from 'vue'
import { useAssignmentStore } from '@/stores/assignment'
import { Card, CardContent } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import Icon from '@/components/ui/Icon.vue'
import clsx from 'clsx'

const store = useAssignmentStore()

const draft = computed(() => store.currentDraft)
const app = computed(() => store.app)
const currentWeekDate = computed(() => store.currentWeekDate)

// 배정된 멤버 수 계산
const assignedCount = computed(() => {
  const assigned = new Set<string>()
  if (!draft.value) return 0
  
  const parts = [draft.value.part1, draft.value.part2]
  parts.forEach(p => {
    if (p.SW) assigned.add(p.SW)
    if (p['자막']) assigned.add(p['자막'])
    if (p['고정']) assigned.add(p['고정'])
    if (p['스케치']) assigned.add(p['스케치'])
    p['사이드'].forEach(n => { if (n) assigned.add(n) })
  })
  
  return assigned.size
})

// 불참자 수
const absentCount = computed(() => {
  return app.value.weeks[currentWeekDate.value]?.absences?.length ?? 0
})

// 총 슬롯 수
const totalSlots = 12 // (SW + 자막 + 고정 + 스케치 + 사이드×2) × 2부

// 채워진 슬롯 수
const filledSlots = computed(() => {
  let count = 0
  if (!draft.value) return 0
  
  const parts = [draft.value.part1, draft.value.part2]
  parts.forEach(p => {
    if (p.SW) count++
    if (p['자막']) count++
    if (p['고정']) count++
    if (p['스케치']) count++
    p['사이드'].forEach(n => { if (n) count++ })
  })
  
  return count
})

const progress = computed(() => Math.round((filledSlots.value / totalSlots) * 100))

// 날짜 포맷
const formattedDate = computed(() => {
  const date = new Date(currentWeekDate.value)
  const month = date.getMonth() + 1
  const day = date.getDate()
  return `${month}월 ${day}일`
})
</script>

<template>
  <Card>
    <CardContent class="p-4 space-y-4">
    <!-- Header -->
    <div class="flex items-center justify-between">
      <div class="flex items-center gap-2">
        <Icon name="CalendarDaysIcon" :size="18" class="text-[var(--color-accent)]" />
        <h3 class="text-sm font-semibold text-[var(--color-label-primary)]">이번 주 배정 현황</h3>
      </div>
      <Badge variant="accent">{{ formattedDate }}</Badge>
    </div>

    <!-- Progress bar -->
    <div class="space-y-2">
      <div class="flex items-center justify-between text-xs">
        <span class="text-[var(--color-label-secondary)]">배정 진행률</span>
        <span class="font-medium text-[var(--color-label-primary)]">{{ filledSlots }}/{{ totalSlots }}</span>
      </div>
      <div class="h-2 bg-[var(--color-surface)] rounded-full overflow-hidden">
        <div 
          :class="clsx(
            'h-full transition-all duration-300 rounded-full',
            progress === 100 ? 'bg-[var(--color-success)]' : 'bg-[var(--color-accent)]'
          )"
          :style="{ width: `${progress}%` }"
        />
      </div>
    </div>

    <!-- Stats -->
    <div class="grid grid-cols-3 gap-2 text-center">
      <div class="p-2 rounded-[var(--radius-sm)] bg-[var(--color-surface)]">
        <div class="text-lg font-bold text-[var(--color-accent)]">{{ assignedCount }}</div>
        <div class="text-xs text-[var(--color-label-tertiary)]">배정된 팀원</div>
      </div>
      <div class="p-2 rounded-[var(--radius-sm)] bg-[var(--color-surface)]">
        <div class="text-lg font-bold text-[var(--color-success)]">{{ progress }}%</div>
        <div class="text-xs text-[var(--color-label-tertiary)]">완료율</div>
      </div>
      <div class="p-2 rounded-[var(--radius-sm)] bg-[var(--color-surface)]">
        <div class="text-lg font-bold text-[var(--color-danger)]">{{ absentCount }}</div>
        <div class="text-xs text-[var(--color-label-tertiary)]">불참자</div>
      </div>
    </div>
    </CardContent>
  </Card>
</template>

// src/features/assignment/components/AssignmentSummary.tsx
'use client'

import { useMemo } from 'react'
import { useAppStore } from '@/shared/state/store'
import { analyzeDraft } from '@/shared/utils/assignment'
import ActivityFeed from '@/shared/components/common/ActivityFeed'
import Icon from '@/shared/components/ui/Icon'
import { Panel } from '@/shared/components/ui/Panel'
import clsx from 'clsx'

type StatusCardProps = {
	icon: string
	label: string
	value: number
	total?: number
	unit?: string
	variant: 'success' | 'warning' | 'default'
	emphasis?: boolean
}

const variantStyles: Record<StatusCardProps['variant'], { iconBg: string; iconText: string; border: string }> = {
	success: {
		iconBg: 'bg-[var(--color-success)]/10',
		iconText: 'text-[var(--color-success)]',
		border: 'border-[var(--color-success)]/20',
	},
	warning: {
		iconBg: 'bg-[var(--color-warning)]/10',
		iconText: 'text-[var(--color-warning)]',
		border: 'border-[var(--color-warning)]/20',
	},
	default: {
		iconBg: 'bg-[var(--color-surface-elevated)]',
		iconText: 'text-[var(--color-label-secondary)]',
		border: 'border-[var(--color-border-default)]',
	},
}

function StatusCard({ icon, label, value, total, unit, variant, emphasis }: StatusCardProps) {
	const styles = variantStyles[variant]

	return (
		<div
			className={clsx(
				'flex items-center gap-3 p-3 rounded-[var(--radius-md)] border transition-colors',
				styles.border,
				emphasis ? 'bg-[var(--color-surface-elevated)]' : 'bg-[var(--color-surface)]'
			)}
		>
			<div className={clsx('w-8 h-8 rounded-[var(--radius-sm)] flex items-center justify-center shrink-0', styles.iconBg)}>
				<Icon name={icon} size={18} className={styles.iconText} />
			</div>
			<div className="flex flex-col min-w-0">
				<span className="text-xs font-medium text-[var(--color-label-secondary)] uppercase tracking-wider">
					{label}
				</span>
				<div className="flex items-baseline gap-0.5">
					<span className="text-lg font-bold text-[var(--color-label-primary)] leading-tight">
						{value}
					</span>
					{typeof total === 'number' && (
						<span className="text-xs text-[var(--color-label-tertiary)]">/{total}</span>
					)}
				</div>
			</div>
		</div>
	)
}

function ProgressBar({ value, label = '진행률' }: { value: number; label?: string }) {
	const clamped = Math.max(0, Math.min(100, Math.round(value)))

	return (
		<div className="mb-4">
			<div className="flex justify-between items-center mb-1.5">
				<span className="text-xs font-semibold text-[var(--color-label-secondary)] uppercase tracking-wide">
					{label}
				</span>
				<span className="text-xs font-bold text-[var(--color-accent)]">{clamped}%</span>
			</div>
			<div className="relative bg-[var(--color-surface-elevated)] h-1.5 rounded-full overflow-hidden">
				<div
					className="absolute left-0 top-0 h-full bg-[var(--color-accent)] rounded-full transition-all duration-500 ease-out"
					style={{ width: `${clamped}%` }}
				/>
			</div>
		</div>
	)
}

export default function AssignmentSummary() {
	const currentWeekDate = useAppStore((s) => s.currentWeekDate)
	const draft = useAppStore((s) => s.currentDraft)
	const warnings = useAppStore((s) => s.warnings)
	const app = useAppStore((s) => s.app)

	const dateLabel = useMemo(() => {
		if (!currentWeekDate) return '주차 미지정'
		const date = new Date(currentWeekDate)
		return date.toLocaleDateString('ko-KR', {
			month: 'long',
			day: 'numeric',
			weekday: 'short'
		})
	}, [currentWeekDate])

	const { total, assigned, emptySlots } = useMemo(() => analyzeDraft(draft), [draft])
	const progressPercent = total === 0 ? 0 : Math.round((assigned / total) * 100)

	// 실제 참석 대상 (전체 멤버 - 불참자)
	const totalActive = app.members.filter(m => m.active !== false).length - (app.weeks[currentWeekDate]?.absences?.length || 0)

	return (
		<Panel className="p-5">
			{/* Header */}
			<div className="flex items-baseline justify-between mb-4">
				<div className="flex items-baseline gap-2">
					<h2 className="text-lg font-bold text-[var(--color-label-primary)] m-0">
						배정 현황
					</h2>
					<span className="text-xs font-medium text-[var(--color-label-tertiary)]">
						{dateLabel}
					</span>
				</div>
			</div>

			{/* Stats Grid */}
			<div className="grid grid-cols-2 lg:grid-cols-4 gap-3 mb-5">
				<StatusCard
					icon="check_circle"
					label="배정 완료"
					value={assigned}
					total={total}
					variant="success"
					emphasis={assigned === total && total > 0}
				/>

				<StatusCard
					icon="groups"
					label="참석 가능"
					value={totalActive}
					unit="명"
					variant="default"
				/>

				<StatusCard
					icon="warning"
					label="이슈"
					value={warnings.length}
					variant="warning"
					emphasis={warnings.length > 0}
				/>

				<StatusCard
					icon="person_off"
					label="미배정 슬롯"
					value={emptySlots.length}
					variant="default"
					emphasis={emptySlots.length > 0}
				/>
			</div>

			{/* Progress Bar */}
			<ProgressBar value={progressPercent} />

			{/* Activity Feed */}
			<div className="pt-4 border-t border-[var(--color-border-subtle)]">
				<ActivityFeed
					title="최근 활동"
					filter={['assignment', 'absence', 'finalize']}
					collapsible={true}
					defaultCollapsed={true}
					maxItems={3}
					emptyMessage="아직 변경 기록이 없습니다."
					showUndo={true}
				/>
			</div>
		</Panel>
	)
}
