// src/features/assignment/components/WarningWidget.tsx
'use client'

import { useState, useMemo } from 'react'
import Icon from '@/shared/components/ui/Icon'
import { useAppStore } from '@/shared/state/store'
import type { Warning } from '@/shared/types'
import { AnimatedCollapse } from '@/shared/components/common/AnimatedCollapse'
import { stripCohort } from '@/shared/utils/assignment'
import clsx from 'clsx'

// ─────────────────────────────────────────────────────────────────────────────
// Styles
// ─────────────────────────────────────────────────────────────────────────────

const levelStyles = {
	error: {
		wrapper: 'bg-[var(--color-danger)]/5 border-[var(--color-danger)]/20',
		icon: 'text-[var(--color-danger)]',
		text: 'text-[var(--color-danger)]',
		subText: 'text-[var(--color-danger)]/80',
	},
	warn: {
		wrapper: 'bg-[var(--color-warning)]/5 border-[var(--color-warning)]/20',
		icon: 'text-[var(--color-warning)]',
		text: 'text-[var(--color-warning)]', // Darker text for readability if needed, or use warning color
		subText: 'text-[var(--color-warning)]/80',
	},
	info: {
		wrapper: 'bg-[var(--color-surface)] border-[var(--color-border-subtle)]',
		icon: 'text-[var(--color-accent)]',
		text: 'text-[var(--color-label-primary)]',
		subText: 'text-[var(--color-label-secondary)]',
	},
}

function FilterChip({
	label,
	count,
	active,
	onClick,
	variant = 'info'
}: {
	label: string
	count: number
	active: boolean
	onClick: () => void
	variant?: 'error' | 'warn' | 'info'
}) {
	const activeClass = variant === 'error' ? 'bg-[var(--color-danger)]/10 text-[var(--color-danger)] ring-1 ring-[var(--color-danger)]/20'
		: variant === 'warn' ? 'bg-[var(--color-warning)]/10 text-[var(--color-warning)] ring-1 ring-[var(--color-warning)]/20'
			: 'bg-[var(--color-surface-elevated)] text-[var(--color-label-primary)] ring-1 ring-[var(--color-border-default)] shadow-sm'

	const inactiveClass = 'bg-transparent text-[var(--color-label-secondary)] border border-[var(--color-border-subtle)] hover:bg-[var(--color-surface)]'

	return (
		<button
			type="button"
			onClick={onClick}
			aria-pressed={active}
			className={clsx(
				'flex items-center gap-1.5 px-2.5 py-1 rounded-full text-xs font-medium transition-all duration-200',
				active ? activeClass : inactiveClass
			)}
		>
			<span>{label}</span>
			{count > 0 && (
				<span className={clsx(
					'px-1.5 py-0.5 rounded-full text-xs',
					active ? 'bg-white/50 backdrop-blur-sm' : 'bg-[var(--color-surface-elevated)]'
				)}>
					{count}
				</span>
			)}
		</button>
	)
}

function WarningItem({ warning }: { warning: Warning }) {
	const styles = levelStyles[warning.level]
	const partLabel = warning.target?.part === 'part1' ? '1부' : warning.target?.part === 'part2' ? '2부' : null

	const iconName = warning.level === 'error' ? 'error'
		: warning.level === 'warn' ? 'warning'
			: 'info'

	const timeMatch = warning.message.match(/\(([^)]+)\)$/)
	const timeContext = timeMatch ? timeMatch[1] : null
	const cleanMessage = timeContext
		? warning.message.replace(/\s*\([^)]+\)$/, '').trim()
		: warning.message

	return (
		<div className={clsx(
			'group relative flex gap-3 p-3 rounded-[var(--radius-md)] border transition-all duration-200 hover:shadow-sm',
			styles.wrapper
		)}>
			{/* Status Icon */}
			<div className={clsx('mt-0.5 shrink-0', styles.icon)}>
				<Icon name={iconName} size={18} />
			</div>

			<div className="flex-1 min-w-0 flex flex-col gap-1.5">
				{/* Top Row: Message & Time */}
				<div className="flex items-start justify-between gap-2">
					<span className={clsx('text-sm font-bold leading-snug', styles.text)}>
						{cleanMessage}
					</span>
					{timeContext && (
						<span className={clsx(
							'shrink-0 text-[11px] font-bold px-1.5 py-0.5 rounded-[4px] border',
							warning.level === 'error'
								? 'bg-[var(--color-danger)]/10 text-[var(--color-danger)] border-[var(--color-danger)]/20'
								: 'bg-[var(--color-warning)]/10 text-[var(--color-warning)] border-[var(--color-warning)]/20'
						)}>
							{timeContext}
						</span>
					)}
				</div>

				{/* Bottom Row: Context Breadcrumbs */}
				<div className="flex items-center flex-wrap gap-1.5 text-xs text-[var(--color-label-secondary)]">
					{(partLabel || warning.target?.role || warning.target?.name) ? (
						<div className="flex items-center gap-1 bg-[var(--color-surface-elevated)] px-1.5 py-0.5 rounded-[4px] border border-[var(--color-border-subtle)]">
							{partLabel && (
								<span className="font-medium text-[var(--color-label-primary)]">{partLabel}</span>
							)}
							{partLabel && warning.target?.role && (
								<Icon name="chevron_right" size={12} className="opacity-50" />
							)}

							{warning.target?.role && (
								<span className="font-medium text-[var(--color-label-primary)]">{warning.target.role}</span>
							)}
							{warning.target?.role && warning.target?.name && (
								<Icon name="chevron_right" size={12} className="opacity-50" />
							)}

							{warning.target?.name && (
								<span className="font-bold text-[var(--color-label-primary)]">
									{stripCohort(warning.target.name)}
								</span>
							)}
						</div>
					) : (
						/* 타겟 정보가 없는 경우 (General Warning) */
						<span className="text-[var(--color-label-tertiary)]">일반 알림</span>
					)}
				</div>
			</div>
		</div>
	)
}

export default function WarningWidget() {
	const warnings = useAppStore((s) => s.warnings || [])
	const [isExpanded, setIsExpanded] = useState(true)
	const [filter, setFilter] = useState<'all' | 'error' | 'warn' | 'info'>('all')

	const counts = useMemo(() => ({
		all: warnings.filter(w => w.level !== 'info').length,
		error: warnings.filter(w => w.level === 'error').length,
		warn: warnings.filter(w => w.level === 'warn').length,
	}), [warnings])

	const visibleWarnings = useMemo(() => {
		let filtered = warnings.filter(w => w.level !== 'info')
		if (filter !== 'all') {
			filtered = filtered.filter(w => w.level === filter)
		}
		const levelRank = { error: 0, warn: 1, info: 2 }
		return [...filtered].sort((a, b) => levelRank[a.level] - levelRank[b.level])
	}, [warnings, filter])

	if (warnings.length === 0) return null

	const hasErrors = counts.error > 0

	return (
		<div className="rounded-[var(--radius-md)] bg-[var(--color-surface)] border border-[var(--color-border-subtle)] shadow-sm overflow-hidden transition-all duration-300">
			{/* Header */}
			<div className={clsx(
				'flex items-center justify-between px-4 py-3 border-b transition-colors cursor-pointer',
				hasErrors
					? 'bg-[var(--color-danger)]/5 border-[var(--color-danger)]/10'
					: 'bg-[var(--color-surface-elevated)] border-[var(--color-border-subtle)]'
			)} onClick={() => setIsExpanded(!isExpanded)}>
				<div className="flex items-center gap-2.5">
					<div className={clsx(
						'relative flex items-center justify-center w-7 h-7 rounded-[var(--radius-sm)]',
						hasErrors
							? 'bg-[var(--color-danger)]/10 text-[var(--color-danger)]'
							: 'bg-[var(--color-surface)] text-[var(--color-label-secondary)] border border-[var(--color-border-subtle)]'
					)}>
						<Icon name={hasErrors ? 'error' : 'notifications'} size={16} />
						{hasErrors && (
							<span className="absolute -top-0.5 -right-0.5 block w-2 h-2 bg-[var(--color-danger)] rounded-full ring-2 ring-white dark:ring-black animate-pulse" />
						)}
					</div>
					<div>
						<h3 className="text-sm font-bold text-[var(--color-label-primary)] leading-none">
							배정 피드백
						</h3>
						<p className="text-xs text-[var(--color-label-secondary)] mt-0.5">
							{counts.all}개의 항목이 있습니다
						</p>
					</div>
				</div>

				<Icon
					name="expand_more"
					size={18}
					className={clsx(
						'text-[var(--color-label-tertiary)] transition-transform duration-200',
						isExpanded && 'rotate-180'
					)}
				/>
			</div>

			{/* Expandable Content */}
			<AnimatedCollapse isOpen={isExpanded}>
				<div className="p-3 bg-[var(--color-canvas)]">
					{/* Filter Chips */}
					<div className="flex items-center gap-2 mb-3 overflow-x-auto pb-1 scrollbar-hide">
						<FilterChip label="전체" count={counts.all} active={filter === 'all'} onClick={() => setFilter('all')} variant="info" />
						{counts.error > 0 && (
							<FilterChip label="긴급" count={counts.error} active={filter === 'error'} onClick={() => setFilter('error')} variant="error" />
						)}
						{counts.warn > 0 && (
							<FilterChip label="주의" count={counts.warn} active={filter === 'warn'} onClick={() => setFilter('warn')} variant="warn" />
						)}

					</div>

					{/* Warning List */}
					<div className="space-y-2">
						{visibleWarnings.length > 0 ? (
							visibleWarnings.map((w) => <WarningItem key={w.id} warning={w} />)
						) : (
							<div className="py-6 text-center text-xs text-[var(--color-label-tertiary)] bg-[var(--color-surface)] rounded-[var(--radius-md)] border border-dashed border-[var(--color-border-subtle)]">
								해당하는 항목이 없습니다
							</div>
						)}
					</div>
				</div>
			</AnimatedCollapse>
		</div>
	)
}

// src/features/assignment/components/WarningWidget.vue
<script setup lang="ts">
import { computed, ref } from 'vue'
import { useAssignmentStore } from '@/stores/assignment'
import type { RoleKey, Warning, WarningLevel } from '@/shared/types'
import { Card, CardContent } from '@/components/ui/card'
import Icon from '@/components/ui/Icon.vue'
import clsx from 'clsx'

type PartKey = 'part1' | 'part2'
type FilterType = 'all' | WarningLevel
type IssueLevel = Exclude<WarningLevel, 'info'>
type InspectTarget = { part?: PartKey; role?: RoleKey; name?: string }

const store = useAssignmentStore()

const activeFilter = ref<FilterType>('all')
const collapsedByLevel = ref<Record<IssueLevel, boolean>>({
  error: false,
  warn: true,
})

const emit = defineEmits<{
  'select-member': [name: string]
  'inspect-target': [target: InspectTarget]
  'recommend-assignment': [payload: { name: string; role: RoleKey }]
}>()

const levelPriority: Record<WarningLevel, number> = {
  error: 0,
  warn: 1,
  info: 2,
}

const sortedWarnings = computed(() => {
  return [...store.warnings].sort((a, b) => {
    const levelDiff = levelPriority[a.level] - levelPriority[b.level]
    if (levelDiff !== 0) return levelDiff
    return a.message.localeCompare(b.message, 'ko')
  })
})

const errorWarnings = computed(() => sortedWarnings.value.filter((w) => w.level === 'error'))
const warnWarnings = computed(() => sortedWarnings.value.filter((w) => w.level === 'warn'))
const infoInsights = computed(() =>
  sortedWarnings.value.filter((w) => w.level === 'info' && !w.rotationCandidates?.length),
)
const rotationSuggestions = computed(() =>
  sortedWarnings.value.filter((w) => w.level === 'info' && !!w.rotationCandidates?.length),
)

const errorCount = computed(() => errorWarnings.value.length)
const warnCount = computed(() => warnWarnings.value.length)
const infoCount = computed(() => store.warnings.filter((w) => w.level === 'info').length)
const totalIssues = computed(() => errorCount.value + warnCount.value)

const summaryText = computed(() => {
  if (errorCount.value > 0) return '즉시 수정이 필요한 배정이 있습니다.'
  if (warnCount.value > 0) return '확정 전 점검 권장 항목이 있습니다.'
  if (infoCount.value > 0) return '참고용 피드백이 있습니다.'
  return '현재 규칙 기준에서 문제 없습니다.'
})

const filterButtons: { key: FilterType; label: string; icon: string }[] = [
  { key: 'all', label: '전체', icon: 'Bars3Icon' },
  { key: 'error', label: '긴급', icon: 'SolidExclamationCircleIcon' },
  { key: 'warn', label: '주의', icon: 'ExclamationTriangleIcon' },
  { key: 'info', label: '정보', icon: 'LightBulbIcon' },
]

function getLevelConfig(level: WarningLevel) {
  const configs = {
    error: {
      icon: 'SolidExclamationCircleIcon',
      borderClass: 'border-l-[var(--color-danger)]',
      badgeClass: 'bg-[var(--color-danger)]/10 text-[var(--color-danger)]',
      label: '긴급',
    },
    warn: {
      icon: 'ExclamationTriangleIcon',
      borderClass: 'border-l-[var(--color-warning)]',
      badgeClass: 'bg-[var(--color-warning)]/10 text-[var(--color-warning)]',
      label: '주의',
    },
    info: {
      icon: 'LightBulbIcon',
      borderClass: 'border-l-[var(--color-accent)]',
      badgeClass: 'bg-[var(--color-accent)]/10 text-[var(--color-accent)]',
      label: '정보',
    },
  }
  return configs[level]
}

function shouldShowLevel(level: IssueLevel): boolean {
  if (activeFilter.value === 'all') return true
  return activeFilter.value === level
}

function getIssueWarnings(level: IssueLevel): Warning[] {
  return level === 'error' ? errorWarnings.value : warnWarnings.value
}

function toggleCollapse(level: IssueLevel) {
  collapsedByLevel.value[level] = !collapsedByLevel.value[level]
}

function formatTarget(warning: Warning): string | null {
  const target = warning.target
  if (!target) return null
  const partLabel = target.part ? (target.part === 'part1' ? '1부' : '2부') : ''
  const roleLabel = target.role ?? ''
  const nameLabel = target.name ?? ''
  const left = [partLabel, roleLabel].filter(Boolean).join(' ')
  const all = [left, nameLabel].filter(Boolean)
  return all.length > 0 ? all.join(' | ') : null
}

function handleWarningClick(warning: Warning) {
  const target = warning.target
  if (!target) return

  if (target.name) {
    emit('select-member', target.name)
  }

  emit('inspect-target', {
    part: target.part,
    role: target.role,
    name: target.name,
  })
}

function handleCandidateClick(suggestion: Warning, candidateName: string) {
  const role = suggestion.target?.role
  if (!role) {
    emit('select-member', candidateName)
    return
  }
  emit('recommend-assignment', { name: candidateName, role })
}

const isInfoEmpty = computed(() => infoInsights.value.length === 0 && rotationSuggestions.value.length === 0)
const isIssuesEmpty = computed(() => {
  if (activeFilter.value === 'error') return errorWarnings.value.length === 0
  if (activeFilter.value === 'warn') return warnWarnings.value.length === 0
  return totalIssues.value === 0
})
</script>

<template>
  <Card>
    <CardContent class="space-y-4 p-4">
      <div class="flex items-center justify-between border-b border-[var(--color-border-subtle)] pb-3">
        <div class="flex items-center gap-2">
          <Icon name="BellIcon" :size="16" class="text-[var(--color-label-tertiary)]" />
          <div>
            <p class="text-sm font-semibold text-[var(--color-label-primary)]">배정 피드백</p>
            <p class="text-xs text-[var(--color-label-tertiary)]">{{ summaryText }}</p>
          </div>
        </div>

        <div class="flex items-center gap-1.5">
          <span v-if="errorCount > 0" class="animate-pulse rounded-[4px] bg-[var(--color-danger)]/10 px-1.5 py-0.5 text-xs font-semibold text-[var(--color-danger)]">
            {{ errorCount }} 긴급
          </span>
          <span v-if="warnCount > 0" class="rounded-[4px] bg-[var(--color-warning)]/10 px-1.5 py-0.5 text-xs font-semibold text-[var(--color-warning)]">
            {{ warnCount }} 주의
          </span>
          <span v-if="infoCount > 0" class="rounded-[4px] bg-[var(--color-accent)]/10 px-1.5 py-0.5 text-xs font-semibold text-[var(--color-accent)]">
            {{ infoCount }} 정보
          </span>
        </div>
      </div>

      <div class="flex flex-wrap gap-1.5">
        <button
          v-for="filter in filterButtons"
          :key="filter.key"
          @click="activeFilter = filter.key"
          :class="clsx(
            'flex cursor-pointer select-none items-center gap-1 rounded-full px-2.5 py-1 text-xs font-medium transition-all duration-150',
            activeFilter === filter.key
              ? 'bg-[var(--color-accent)] text-white'
              : 'bg-[var(--color-surface)] text-[var(--color-label-secondary)] hover:bg-[var(--color-surface-elevated)] active:scale-95',
          )"
        >
          <Icon :name="filter.icon" :size="12" />
          {{ filter.label }}
          <span v-if="filter.key === 'error' && errorCount > 0" class="ml-0.5 text-[10px] opacity-80">({{ errorCount }})</span>
          <span v-else-if="filter.key === 'warn' && warnCount > 0" class="ml-0.5 text-[10px] opacity-80">({{ warnCount }})</span>
          <span v-else-if="filter.key === 'info' && infoCount > 0" class="ml-0.5 text-[10px] opacity-80">({{ infoCount }})</span>
        </button>
      </div>

      <div v-if="activeFilter !== 'info'" class="space-y-2">
        <div v-for="level in (['error', 'warn'] as IssueLevel[])" :key="level" v-show="shouldShowLevel(level)">
          <template v-if="getIssueWarnings(level).length > 0">
            <button
              type="button"
              class="flex w-full items-center justify-between rounded-[var(--radius-sm)] border border-[var(--color-border-subtle)] bg-[var(--color-surface)] px-2.5 py-2 text-left"
              @click="toggleCollapse(level)"
            >
              <div class="flex items-center gap-2">
                <Icon :name="getLevelConfig(level).icon" :size="14" />
                <span class="text-xs font-semibold text-[var(--color-label-secondary)]">
                  {{ getLevelConfig(level).label }} {{ getIssueWarnings(level).length }}건
                </span>
              </div>
              <Icon :name="collapsedByLevel[level] ? 'ChevronDownIcon' : 'ChevronUpIcon'" :size="14" class="text-[var(--color-label-tertiary)]" />
            </button>

            <div v-if="!collapsedByLevel[level]" class="mt-2 space-y-2 max-h-[260px] overflow-y-auto scroll-mask-y">
              <div
                v-for="warning in getIssueWarnings(level)"
                :key="warning.id"
                @click="handleWarningClick(warning)"
                :class="clsx(
                  'relative flex cursor-pointer items-start gap-3 rounded-[var(--radius-sm)] border-l-[3px] bg-[var(--color-surface)] p-3 transition-all duration-150 hover:bg-[var(--color-surface-elevated)] active:scale-[0.98]',
                  getLevelConfig(warning.level).borderClass,
                )"
              >
                <div
                  :class="clsx(
                    'flex h-7 w-7 flex-shrink-0 items-center justify-center rounded-full',
                    warning.level === 'error'
                      ? 'bg-[var(--color-danger)]/10 text-[var(--color-danger)]'
                      : 'bg-[var(--color-warning)]/10 text-[var(--color-warning)]',
                  )"
                >
                  <Icon :name="getLevelConfig(warning.level).icon" :size="14" :class="warning.level === 'error' ? 'animate-pulse' : ''" />
                </div>

                <div class="min-w-0 flex-1">
                  <div class="mb-0.5 flex items-center gap-2">
                    <span :class="clsx('rounded-[3px] px-1.5 py-0.5 text-[10px] font-semibold uppercase tracking-wide', getLevelConfig(warning.level).badgeClass)">
                      {{ getLevelConfig(warning.level).label }}
                    </span>
                    <span v-if="formatTarget(warning)" class="rounded-[3px] bg-[var(--color-surface-elevated)] px-1.5 py-0.5 text-xs font-medium text-[var(--color-label-primary)]">
                      {{ formatTarget(warning) }}
                    </span>
                  </div>
                  <p class="text-sm leading-relaxed text-[var(--color-label-secondary)]">{{ warning.message }}</p>
                </div>
              </div>
            </div>
          </template>
        </div>
      </div>

      <div v-if="activeFilter === 'info'" class="space-y-3">
        <div v-if="infoInsights.length > 0" class="space-y-2">
          <p class="px-1 text-xs font-semibold text-[var(--color-label-tertiary)]">관찰 정보</p>
          <div class="space-y-2 max-h-[180px] overflow-y-auto scroll-mask-y">
            <div
              v-for="insight in infoInsights"
              :key="insight.id"
              class="cursor-pointer rounded-[var(--radius-sm)] border-l-[3px] border-l-[var(--color-accent)] bg-[var(--color-surface)] p-3 transition-colors hover:bg-[var(--color-surface-elevated)]"
              @click="handleWarningClick(insight)"
            >
              <div class="flex items-start gap-2">
                <div class="mt-0.5 flex h-6 w-6 items-center justify-center rounded-full bg-[var(--color-accent)]/10 text-[var(--color-accent)]">
                  <Icon name="InformationCircleIcon" :size="12" />
                </div>
                <div class="min-w-0">
                  <p class="text-sm leading-relaxed text-[var(--color-label-secondary)]">{{ insight.message }}</p>
                  <p v-if="formatTarget(insight)" class="mt-1 text-xs text-[var(--color-label-tertiary)]">{{ formatTarget(insight) }}</p>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div v-if="rotationSuggestions.length > 0" class="space-y-2">
          <p class="px-1 text-xs font-semibold text-[var(--color-label-tertiary)]">로테이션 추천</p>
          <div class="space-y-3 max-h-[260px] overflow-y-auto scroll-mask-y">
            <div
              v-for="suggestion in rotationSuggestions"
              :key="suggestion.id"
              class="rounded-[var(--radius-sm)] border-l-[3px] border-l-[var(--color-accent)] bg-[var(--color-surface)] p-3"
            >
              <div class="mb-2 flex items-center gap-2">
                <div class="flex h-6 w-6 items-center justify-center rounded-full bg-[var(--color-accent)]/10 text-[var(--color-accent)]">
                  <Icon name="LightBulbIcon" :size="12" />
                </div>
                <span class="text-sm font-semibold text-[var(--color-label-primary)]">{{ suggestion.message }}</span>
              </div>

              <div v-if="suggestion.rotationCandidates" class="mt-2 flex flex-wrap gap-1.5">
                <button
                  v-for="(candidate, index) in suggestion.rotationCandidates"
                  :key="candidate.name"
                  type="button"
                  @click="handleCandidateClick(suggestion, candidate.name)"
                  :class="clsx(
                    'inline-flex cursor-pointer items-center gap-1 rounded-full border px-2 py-0.5 text-xs transition-colors active:scale-95',
                    'border-[var(--color-border-subtle)] hover:border-[var(--color-accent)]',
                    index === 0
                      ? 'border-[var(--color-accent)]/30 bg-[var(--color-accent)]/10 font-medium text-[var(--color-accent)]'
                      : 'bg-[var(--color-surface-elevated)] text-[var(--color-label-secondary)]',
                  )"
                >
                  {{ candidate.name }}
                  <span class="text-[10px] opacity-70">
                    {{ candidate.weeksSince === Infinity ? '미배정' : `${candidate.weeksSince}주↑` }}
                  </span>
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div v-if="(activeFilter !== 'info' && isIssuesEmpty) || (activeFilter === 'info' && isInfoEmpty)" class="py-8 text-center">
        <div class="mx-auto mb-3 flex h-12 w-12 items-center justify-center rounded-full bg-[var(--color-surface)]">
          <Icon :name="activeFilter === 'info' ? 'LightBulbIcon' : 'SolidCheckCircleIcon'" :size="24" class="text-[var(--color-success)]" />
        </div>
        <p class="text-sm text-[var(--color-label-secondary)]">
          {{ activeFilter === 'info' ? '현재 추천 사항이 없습니다.' : '모든 배정이 적절합니다!' }}
        </p>
        <p v-if="activeFilter !== 'info'" class="mt-1 text-xs text-[var(--color-label-tertiary)]">
          연속 배정 경고가 없습니다
        </p>
      </div>

      <div
        v-if="totalIssues === 0 && activeFilter === 'all'"
        class="flex items-center justify-center gap-1 border-t border-[var(--color-border-subtle)] pt-2 text-center text-xs text-[var(--color-label-tertiary)]"
      >
        <Icon name="LightBulbIcon" :size="12" class="text-[var(--color-accent)]" />
        '정보' 탭에서 로테이션 제안을 확인하세요
      </div>
    </CardContent>
  </Card>
</template>
