// src/components/common/ThemeToggle.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useThemeStore } from '@/stores/theme'
import Icon from '@/components/ui/Icon.vue'
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from '@/components/ui/tooltip'

const themeStore = useThemeStore()

function cycleTheme() {
  const themes = ['light', 'dark', 'system'] as const
  const currentIndex = themes.indexOf(themeStore.theme)
  const nextIndex = (currentIndex + 1) % themes.length
  themeStore.setTheme(themes[nextIndex])
}

function getIcon() {
  if (themeStore.theme === 'system') return 'computer'
  return themeStore.theme === 'dark' ? 'dark_mode' : 'light_mode'
}

const themeLabel = computed(() => {
  const labels = {
    light: '라이트 모드',
    dark: '다크 모드',
    system: '시스템 설정'
  }
  return labels[themeStore.theme]
})
</script>

<template>
  <TooltipProvider>
    <Tooltip>
      <TooltipTrigger asChild>
        <button
          @click="cycleTheme"
          class="icon-btn"
          aria-label="Toggle theme"
        >
          <Icon :name="getIcon()" :size="18" />
        </button>
      </TooltipTrigger>
      <TooltipContent>
        <p>테마: {{ themeLabel }}</p>
      </TooltipContent>
    </Tooltip>
  </TooltipProvider>
</template>

// src/components/common/ThemeToggle.tsx
import { useAppStore } from '../../state/store'

export default function ThemeToggle() {
	const theme = useAppStore((s) => s.theme)
	const setTheme = useAppStore((s) => s.setTheme)

	// 시스템 모드인 경우 라이트 모드로 변환
	const currentTheme = theme === 'system' ? 'light' : theme

	function cycleTheme() {
		if (currentTheme === 'light') {
			setTheme('dark')
		} else {
			setTheme('light')
		}
	}

	const iconMap: Record<'light' | 'dark', string> = {
		light: 'light_mode',
		dark: 'dark_mode'
	}
	const labelMap: Record<'light' | 'dark', string> = {
		light: '라이트 모드',
		dark: '다크 모드'
	}

	const nextTheme = currentTheme === 'light' ? 'dark' : 'light'
	const nextLabel = nextTheme === 'light' ? '라이트 모드로 전환' : '다크 모드로 전환'

	return (
		<button
			className="btn theme-toggle"
			onClick={cycleTheme}
			aria-label={`현재 ${labelMap[currentTheme]}. ${nextLabel}`}
			title={`${labelMap[currentTheme]} · ${nextLabel}`}
		>
			<span className="material-symbol theme-toggle__icon" aria-hidden="true">
				{iconMap[currentTheme]}
			</span>
		</button>
	)
}
