// src/shared/components/common/AnimatedCollapse.vue
<script setup lang="ts">
/**
 * AnimatedCollapse.vue - 접기/펼치기 애니메이션 컨테이너
 * 
 * - Vue 3 Transition API를 사용하여 높이/페이드 애니메이션 제공
 * - prefers-reduced-motion 미디어 쿼리 존중
 */
import { computed } from 'vue'

interface Props {
  /**
   * 표시 여부
   */
  isOpen: boolean
  /**
   * 애니메이션 유형
   * - 'height': 높이 변화 (접기/펼치기)
   * - 'fade': 페이드 인/아웃
   */
  variant?: 'height' | 'fade'
  /**
   * 래퍼 클래스명
   */
  className?: string
}

const props = withDefaults(defineProps<Props>(), {
  variant: 'height',
  className: 'overflow-hidden'
})

// 모션 감소 설정 확인
const shouldReduceMotion = computed(() => {
  if (typeof window === 'undefined') return false
  return window.matchMedia?.('(prefers-reduced-motion: reduce)')?.matches ?? false
})

// 높이 애니메이션 핸들러
function onEnter(el: HTMLElement) {
  if (props.variant === 'fade') {
    el.style.opacity = '0'
    return
  }
  // 높이 애니메이션
  el.style.height = '0'
  el.style.opacity = '0'
  el.offsetHeight // force reflow
  el.style.transition = 'height 0.3s cubic-bezier(0.4, 0, 0.2, 1), opacity 0.3s ease'
  el.style.height = el.scrollHeight + 'px'
  el.style.opacity = '1'
}

function onAfterEnter(el: HTMLElement) {
  if (props.variant === 'height') {
    el.style.height = 'auto'
  }
  el.style.transition = ''
}

function onLeave(el: HTMLElement) {
  if (props.variant === 'fade') {
    el.style.opacity = '0'
    return
  }
  // 높이 애니메이션
  el.style.height = el.scrollHeight + 'px'
  el.offsetHeight // force reflow
  el.style.transition = 'height 0.25s cubic-bezier(0.4, 0, 0.2, 1), opacity 0.25s ease'
  el.style.height = '0'
  el.style.opacity = '0'
}

function onAfterLeave(el: HTMLElement) {
  el.style.height = ''
  el.style.opacity = ''
  el.style.transition = ''
}

// 페이드 애니메이션용
function onFadeEnter(el: HTMLElement) {
  el.style.opacity = '0'
  el.style.transform = 'translateY(5px)'
  el.offsetHeight
  el.style.transition = 'opacity 0.15s ease, transform 0.15s ease'
  el.style.opacity = '1'
  el.style.transform = 'translateY(0)'
}

function onFadeLeave(el: HTMLElement) {
  el.style.transition = 'opacity 0.15s ease, transform 0.15s ease'
  el.style.opacity = '0'
  el.style.transform = 'translateY(-5px)'
}
</script>

<template>
  <!-- 모션 감소 모드: 애니메이션 없이 즉시 표시/숨김 -->
  <template v-if="shouldReduceMotion">
    <div v-if="isOpen" :class="className">
      <slot />
    </div>
  </template>

  <!-- 일반 모드: 애니메이션 적용 -->
  <Transition
    v-else
    :css="false"
    @enter="variant === 'fade' ? onFadeEnter($event as HTMLElement) : onEnter($event as HTMLElement)"
    @after-enter="onAfterEnter($event as HTMLElement)"
    @leave="variant === 'fade' ? onFadeLeave($event as HTMLElement) : onLeave($event as HTMLElement)"
    @after-leave="onAfterLeave($event as HTMLElement)"
    mode="out-in"
  >
    <div v-if="isOpen" :class="className">
      <slot />
    </div>
  </Transition>
</template>

// src/shared/components/common/AnimatedCollapse.tsx
'use client'

import { ReactNode } from 'react'
import { AnimatePresence, m, LazyMotion, domAnimation } from 'framer-motion'
import { useShouldReduceMotion } from '@/shared/utils/motion'

type AnimatedCollapseProps = {
    /**
     * 표시 여부
     */
    isOpen: boolean
    /**
     * 자식 컴포넌트
     */
    children: ReactNode
    /**
     * 애니메이션 키 (탭 전환 등에서 사용)
     */
    animationKey?: string
    /**
     * 애니메이션 유형
     * - 'height': 높이 변화 (접기/펼치기)
     * - 'fade': 페이드 인/아웃
     */
    variant?: 'height' | 'fade'
    /**
     * 래퍼 클래스명
     */
    className?: string
}

const heightAnimation = {
    initial: { height: 0, opacity: 0 },
    animate: { height: 'auto', opacity: 1 },
    exit: { height: 0, opacity: 0 },
    transition: { type: 'spring' as const, stiffness: 400, damping: 35 }
}

const fadeAnimation = {
    initial: { opacity: 0, y: 5 },
    animate: { opacity: 1, y: 0 },
    exit: { opacity: 0, y: -5 },
    transition: { duration: 0.15 }
}

/**
 * 모션 감소 설정을 존중하는 애니메이션 컨테이너
 * 
 * - prefers-reduced-motion이 활성화되면 애니메이션 없이 렌더링
 * - LazyMotion을 사용하여 framer-motion 번들 크기 최적화
 */
export function AnimatedCollapse({
    isOpen,
    children,
    animationKey = 'content',
    variant = 'height',
    className = 'overflow-hidden'
}: AnimatedCollapseProps) {
    const shouldReduce = useShouldReduceMotion()
    const animation = variant === 'height' ? heightAnimation : fadeAnimation

    // 모션 감소 모드: 애니메이션 없이 즉시 표시/숨김
    if (shouldReduce) {
        if (!isOpen) return null
        return <div className={className}>{children}</div>
    }

    // 일반 모드: 애니메이션 적용
    return (
        <LazyMotion features={domAnimation} strict>
            <AnimatePresence mode="wait" initial={false}>
                {isOpen && (
                    <m.div
                        key={animationKey}
                        initial={animation.initial}
                        animate={animation.animate}
                        exit={animation.exit}
                        transition={animation.transition}
                        className={className}
                    >
                        {children}
                    </m.div>
                )}
            </AnimatePresence>
        </LazyMotion>
    )
}
