// src/components/common/Modal.vue
<script setup lang="ts">
/**
 * Modal.vue - shadcn Dialog + @vueuse/motion 기반 모달
 * 
 * 기존 인터페이스를 유지하면서 shadcn Dialog로 마이그레이션
 */
import { computed, watch, onUnmounted } from 'vue'
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from '@/components/ui/dialog'
import { X } from 'lucide-vue-next'

type ModalSize = 'sm' | 'md' | 'lg' | 'xl' | 'full'

interface Props {
  open: boolean
  title?: string
  size?: ModalSize
}

const props = withDefaults(defineProps<Props>(), {
  open: false,
  size: 'md'
})

const emit = defineEmits<{
  close: []
}>()

// Size mapping to Tailwind classes
const sizeClasses = computed(() => {
  const sizes: Record<ModalSize, string> = {
    sm: 'sm:max-w-sm',
    md: 'sm:max-w-md',
    lg: 'sm:max-w-lg',
    xl: 'sm:max-w-xl',
    full: 'sm:max-w-[calc(100vw-2rem)] h-[calc(100vh-2rem)]',
  }
  return sizes[props.size]
})

function handleOpenChange(value: boolean) {
  if (!value) {
    emit('close')
  }
}

// Handle body scroll lock
watch(() => props.open, (newVal) => {
  if (newVal) {
    document.body.style.overflow = 'hidden'
  } else {
    document.body.style.overflow = 'unset'
  }
}, { immediate: true })

onUnmounted(() => {
  document.body.style.overflow = 'unset'
})
</script>

<template>
  <Dialog :open="open" @update:open="handleOpenChange">
    <DialogContent
      v-motion
      :initial="{ opacity: 0, scale: 0.95, y: 20 }"
      :enter="{ 
        opacity: 1, 
        scale: 1, 
        y: 0, 
        transition: { type: 'spring', stiffness: 300, damping: 25 } 
      }"
      :class="[
        'bg-[var(--color-surface-elevated)] border-[var(--color-border-subtle)]',
        'rounded-[var(--radius-lg)] p-0 gap-0',
        sizeClasses
      ]"
      :show-close-button="false"
    >
      <!-- Header -->
      <DialogHeader 
        v-if="title"
        class="flex flex-row items-center justify-between px-5 py-4 border-b border-[var(--color-border-subtle)] space-y-0"
      >
        <DialogTitle class="text-lg font-semibold text-[var(--color-label-primary)]">
          {{ title }}
        </DialogTitle>
        <button
          type="button"
          @click="emit('close')"
          class="p-1 rounded-[var(--radius-sm)] text-[var(--color-label-tertiary)] hover:bg-[var(--color-surface)] hover:text-[var(--color-label-secondary)] transition-colors"
        >
          <X class="w-5 h-5" />
        </button>
      </DialogHeader>

      <!-- Body -->
      <div class="p-5 overflow-y-auto max-h-[70vh]">
        <slot />
      </div>

      <!-- Footer -->
      <DialogFooter
        v-if="$slots.footer"
        class="flex items-center justify-end gap-2 px-5 py-4 bg-[var(--color-surface)]/50 border-t border-[var(--color-border-subtle)] rounded-b-[var(--radius-lg)]"
      >
        <slot name="footer" />
      </DialogFooter>
    </DialogContent>
  </Dialog>
</template>

// src/shared/components/common/Modal.tsx
'use client'

import { useEffect, useState } from 'react'
import { createPortal } from 'react-dom'
import type { ReactNode } from 'react'
import Icon from '../ui/Icon'
import { Button } from '../ui/Button'
import clsx from 'clsx'

type ModalSize = 'sm' | 'md' | 'lg' | 'xl' | 'full'

interface ModalProps {
    open: boolean
    onClose: () => void
    title?: string
    children: ReactNode
    footer?: ReactNode
    size?: ModalSize
}

const sizes: Record<ModalSize, string> = {
    sm: 'max-w-sm',
    md: 'max-w-md',
    lg: 'max-w-lg',
    xl: 'max-w-xl',
    full: 'max-w-full m-4',
}

export default function Modal({
    open,
    onClose,
    title,
    children,
    footer,
    size = 'md',
}: ModalProps) {
    const [mounted, setMounted] = useState(false)
    const [isVisible, setIsVisible] = useState(false)

    useEffect(() => {
        setMounted(true)
    }, [])

    useEffect(() => {
        if (open) {
            setIsVisible(true)
            document.body.style.overflow = 'hidden'
        } else {
            const timer = setTimeout(() => setIsVisible(false), 200)
            document.body.style.overflow = 'unset'
            return () => clearTimeout(timer)
        }
    }, [open])

    if (!mounted) return null
    if (!isVisible && !open) return null

    return createPortal(
        <div
            className={clsx(
                'fixed inset-0 z-50 flex items-center justify-center p-4',
                'transition-opacity duration-200',
                open ? 'opacity-100' : 'opacity-0'
            )}
        >
            {/* Backdrop */}
            <div
                className="absolute inset-0 bg-black/40 backdrop-blur-sm transition-opacity"
                onClick={onClose}
            />

            {/* Modal Content */}
            <div
                className={clsx(
                    'relative w-full bg-[var(--color-surface-elevated)]',
                    'rounded-[var(--radius-lg)] shadow-xl',
                    'border border-[var(--color-border-subtle)]',
                    'transform transition-all duration-200',
                    open ? 'scale-100 translate-y-0' : 'scale-95 translate-y-2',
                    sizes[size]
                )}
            >
                {/* Header */}
                <div className="flex items-center justify-between px-5 py-4 border-b border-[var(--color-border-subtle)]">
                    <h3 className="text-lg font-semibold text-[var(--color-label-primary)]">
                        {title}
                    </h3>
                    <button
                        onClick={onClose}
                        className="p-1 rounded-[var(--radius-sm)] text-[var(--color-label-tertiary)] hover:bg-[var(--color-surface)] hover:text-[var(--color-label-secondary)] transition-colors"
                    >
                        <Icon name="close" size={20} />
                    </button>
                </div>

                {/* Body */}
                <div className="p-5 overflow-y-auto max-h-[70vh]">
                    {children}
                </div>

                {/* Footer */}
                {footer && (
                    <div className="flex items-center justify-end gap-2 px-5 py-4 bg-[var(--color-surface)]/50 border-t border-[var(--color-border-subtle)] rounded-b-[var(--radius-lg)]">
                        {footer}
                    </div>
                )}
            </div>
        </div>,
        document.body
    )
}
